services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    \Zantolov\ZoogleCms\Infrastructure\GoogleDrive\Content\Converting\Document\ElementConverter:
      tags: [ 'zoogle_document_converter' ]

  Zantolov\ZoogleCms\Infrastructure\:
    resource: '../*'

  Zantolov\ZoogleCms\Infrastructure\GoogleDrive\Client\GoogleDriveAuth:
    arguments:
      $authConfigPath: '%kernel.project_dir%/%env(GOOGLE_DRIVE_API_AUTH_FILE_PATH)%'
      $clientId: '%env(GOOGLE_DRIVE_API_CLIENT_ID)%'

  Zantolov\ZoogleCms\Infrastructure\GoogleDrive\Client\CachedGoogleDriveClient:
    arguments:
      $client: '@Zantolov\ZoogleCms\Infrastructure\GoogleDrive\Client\BaseGoogleDriveClient'

  Zantolov\ZoogleCms\Infrastructure\GoogleDrive\Client\GoogleDriveClientFactory: ~

  Zantolov\ZoogleCms\Infrastructure\GoogleDrive\Client\GoogleDriveClient:
    factory: [ '@Zantolov\ZoogleCms\Infrastructure\GoogleDrive\Client\GoogleDriveClientFactory', 'create' ]
    arguments:
      $useCache: '%env(bool:ZOOGLE_CACHE)%'

  Zantolov\ZoogleCms\Infrastructure\GoogleDrive\Configuration\Configuration:
    arguments:
      $rootDirectoryId: '%env(GOOGLE_DRIVE_ROOT_DIRECTORY_ID)%'

  Zantolov\ZoogleCms\Infrastructure\GoogleDrive\Content\Converting\Document\Converter:
    arguments:
      $converters: !tagged_iterator zoogle_document_converter
