name: "CI"

on:
    pull_request:
    push:
        branches:
            - "master"

jobs:
    ci:
        name: "CI Pipeline"
        runs-on: [ "ubuntu-latest" ]
        env:
            DOCKER_BUILDKIT: 1
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    push: false
                    context: .
                    file: infrastructure/Dockerfile
#      - name: Build Docker image
#        run: |
#          cd $RUN_FOLDER \
#          && DOCKER_BUILDKIT=1 docker build -f infrastructure/Dockerfile .
